### PR TITLE
blur util

### PR DESCRIPTION
**Pull request by sumeshir26**

### CODE REVIEW

**Comment by not-nef** [comment]
@sumeshir26 Did you test it?

**Comment by sumeshir26** [comment]
@not-nef

**Comment by not-nef** [comment]
@sumeshir26 Are you ok with the changes i made?

**Comment by sumeshir26** [comment]
yup, this is your projects, you dont need to ask
FYI, you arent watching this repo. i was confused why you didnt respond so i mentioned you

**Comment by not-nef** [comment]
I did see this, but i had an extreme headache the last days so i had no time to test and eventually forgot about it. Sorry for the inconvenience!

**Comment by sumeshir26** [comment]
np

**Pull request merged**
